name: ci
on:
  push:
    branches:
      - master
      - main
      - refractor-ui

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Setup npm
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy - Checkout gh-pages branch
        run: |
          git fetch origin
          git checkout -b gh-pages origin/gh-pages || git checkout --orphan gh-pages

      - name: Deploy - Clear old contents
        run: |
          rm -rf *

      - name: Deploy - Copy new contents
        run: |
          cp -r dist/* .

      - name: Deploy - Commit changes
        run: |
          git add .
          git commit -m 'Deploy to GitHub Pages'

      - name: Deploy - Push to gh-pages
        run: |
          git push origin gh-pages --force
